[package]
name = "kornia-vlm-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
ndarray = "0.17.2"
ort = { version = "2.0.0-rc.11", features = ["ndarray"] }
image = "0.24"
